sources:
  - name: openai
    repo: https://github.com/openai/skills
    paths:
      - .curated

  - name: anthropic
    repo: https://github.com/anthropics/skills
    paths:
      - .

  - name: antigravity
    repo: https://github.com/sickn33/antigravity-awesome-skills
    paths:
      - .

  - name: openclaw
    repo: https://github.com/openclaw/skills
    paths:
      - .
